create and style header
RobMota/clone-wwf-homepage-html-css pull request #1
Opened 2020-09-22 03:32 UTC by RobMota

Verificar se esta tudo ok com o cabeçalho ( header da página )

2020-09-23 13:55 UTC, moschiel requested changes
O logo do panda nao esta carregando no header.
Acho que tambem seria uma boa ideia ter uma pasta **css** separada para os arquivos CSS
tipo **css/style.css**
![image](https://user-images.githubusercontent.com/45469807/94022092-1f8f7c00-fd8b-11ea-9734-383de689aef5.png)
No aguardo das alteracoes solicitadas para poder aprovar.

2020-09-25 15:49 UTC, RobMota commented
Obrigado.
Está ok agora.👍

2020-09-30 19:27 UTC, moschiel reviewed
Esta ok boss, pode fazer o merge

2020-09-30 19:28 UTC, moschiel approved these changes
Esta ok Boss, pode fazer o merge

2020-09-30 20:31 UTC, merged